---
name: idr0086-miron-micrographs/experimentC
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Experimental Condition [Treatment]
    clientname: Treatment
    include: yes

  - name: Experimental Condition [Marker]
    clientname: Marker
    include: yes

  - name: Comment [Assay Description]
    clientname: Assay Description
    include: yes

  - name: Comment [Image Description]
    clientname: Image Description
    include: yes

  - name: Channels
    clientname: Channels
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
        - name: Characteristics [Cell Line]
          clientname: Cell Line
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
        - name: Comment [Gene Identifier]
          clientname: Gene Identifier
          include: yes
        - name: Comment [Gene Identifier]
          clientname: Gene Identifier URL
          clientvalue: http://www.ensembl.org/id/{{ value|urlencode }}
          include: yes
        - name: Comment [Gene Symbol]
          clientname: Gene Symbol
          include: yes


advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
        - Cell Line
    - namespace: openmicroscopy.org/mapr/gene
      keys:
        - Gene Identifier
        - Gene Symbol
